# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow2(object):
    def setupUi(self, MainWindow2):
        MainWindow2.setObjectName("MainWindow2")
        MainWindow2.resize(1036, 488)
        self.centralwidget = QtWidgets.QWidget(MainWindow2)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 468, 113))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.stupid = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        self.stupid.setFont(font)
        self.stupid.setObjectName("stupid")
        self.gridLayout.addWidget(self.stupid, 0, 0, 1, 1)
        self.chet_nechet = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.chet_nechet.setObjectName("chet_nechet")
        self.gridLayout.addWidget(self.chet_nechet, 1, 1, 1, 1)
        self.gnom = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.gnom.setObjectName("gnom")
        self.gridLayout.addWidget(self.gnom, 1, 0, 1, 1)
        self.bubble = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.bubble.setObjectName("bubble")
        self.gridLayout.addWidget(self.bubble, 0, 1, 1, 1)
        self.comb = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.comb.setObjectName("comb")
        self.gridLayout.addWidget(self.comb, 1, 2, 1, 1)
        self.ba_ma_shegi_ba = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ba_ma_shegi_ba.setObjectName("ba_ma_shegi_ba")
        self.gridLayout.addWidget(self.ba_ma_shegi_ba, 0, 2, 1, 1)
        self.insertion = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.insertion.setObjectName("insertion")
        self.gridLayout.addWidget(self.insertion, 2, 0, 1, 1)
        self.pair_insertion = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pair_insertion.setObjectName("pair_insertion")
        self.gridLayout.addWidget(self.pair_insertion, 2, 1, 1, 1)
        self.shell = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.shell.setObjectName("shell")
        self.gridLayout.addWidget(self.shell, 3, 1, 1, 1)
        self.selection = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.selection.setObjectName("selection")
        self.gridLayout.addWidget(self.selection, 2, 2, 1, 1)
        self.quick = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.quick.setObjectName("quick")
        self.gridLayout.addWidget(self.quick, 3, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 130, 461, 31))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label3 = QtWidgets.QLabel(self.centralwidget)
        self.label3.setGeometry(QtCore.QRect(20, 170, 401, 461))
        self.label3.setText("")
        self.label3.setObjectName("label3")
        self.label4 = QtWidgets.QLabel(self.centralwidget)
        self.label4.setGeometry(QtCore.QRect(160, 160, 851, 91))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label4.setFont(font)
        self.label4.setText("")
        self.label4.setObjectName("label4")
        MainWindow2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1036, 21))
        self.menubar.setObjectName("menubar")
        MainWindow2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow2)
        self.statusbar.setObjectName("statusbar")
        MainWindow2.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow2)

    def retranslateUi(self, MainWindow2):
        _translate = QtCore.QCoreApplication.translate
        MainWindow2.setWindowTitle(_translate("MainWindow2", "MainWindow"))
        self.stupid.setText(_translate("MainWindow2", "глупая сортировка"))
        self.chet_nechet.setText(_translate("MainWindow2", "сортировка чёт-нечёт"))
        self.gnom.setText(_translate("MainWindow2", "гномья сортировка"))
        self.bubble.setText(_translate("MainWindow2", "сортировка пузырьком"))
        self.comb.setText(_translate("MainWindow2", "сортировка расчёской"))
        self.ba_ma_shegi_ba.setText(_translate("MainWindow2", "шейкерная сортировка"))
        self.insertion.setText(_translate("MainWindow2", "сортировка вставками"))
        self.pair_insertion.setText(_translate("MainWindow2", "парная сортировка вставками"))
        self.shell.setText(_translate("MainWindow2", "сортировка Шелла"))
        self.selection.setText(_translate("MainWindow2", "сортировка выбором"))
        self.quick.setText(_translate("MainWindow2", "быстрая сортировка"))

